name: B P M P
favicon: null
layout_spectrum: 0.09473975887522101
typography_spectrum: 0.16190090426243842
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.006477429764345288
  lightness: 0.693718122318387
  saturation: 0.5989749988075346
  rhythmicContrast: 0.5930085063446313
purpose: []
